version: "3"
services:
  graphql:
    depends_on:
      - mongodb
    image: app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: bash -c "composer install && php -S 0.0.0.0:8080 public/graphql.php"
  frontend:
    depends_on:
      - graphql
      - mongodb
    image: app
    ports:
      - "8081:8080"
    volumes:
      - .:/usr/src/app
    command: php -S 0.0.0.0:8080 public/frontend.php
  mongodb:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-data:/data
  graphiql:
    depends_on:
      - graphql
    image: npalm/graphiql
    ports:
      - "4000:4000"
    environment:
      - API_URL=http://localhost:8080
  voyager:
    depends_on:
      - graphql
    image: atten/graphql-voyager
    ports:
      - "9090:9090"
    environment:
      - GRAPHQL_SCHEMA_URL=http://localhost:8080/graphql
